name: Test

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: "adopt@1.11"

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Check format
        run: |
          mkdir -p dist
          sbt -no-colors checkAll > dist/result.txt

      - name: Test
        run: 'sbt "testOnly com.nulabinc.*"'

      - name: Upload sbt result
        uses: actions/upload-artifact@master
        with:
          name: sbt-result
          path: dist
